Bookmark.create(name: "How to learn Emacs :: The very basics ", link: "http://david.rothlis.net/emacs/tutorial.html")
Bookmark.create(name: "The Rust Programming Language ", link: "http://doc.rust-lang.org/stable/book/")
Bookmark.create(name: "Formatted print | Rust by Example ", link: "http://rustbyexample.com/hello/print.html")
Bookmark.create(name: "Eloquent JavaScript ", link: "http://eloquentjavascript.net/")
Bookmark.create(name: "HAML", link: "http://haml.info/")